site_name: METAL ARMS DOCS
site_url: ""
use_directory_urls: false
extra_css:
    - stylesheets/extra.css
plugins:
    - search
    - localsearch
theme:
    name: material
    custom_dir: theme
    palette:
        - scheme: slate
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
nav:
    - Home: index.md
    - File Formats: fileformats.md
    - Level Names: levels.md
    - Star Commands: starcommands.md
    - Gamedata: userdata.md
